-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "foundation_spike";

-- CreateTable
CREATE TABLE "foundation_spike"."transaction_probe" (
    "id" UUID NOT NULL,
    "label" TEXT NOT NULL,
    "counter" INTEGER NOT NULL DEFAULT 0,

    CONSTRAINT "transaction_probe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "foundation_spike"."job_claim" (
    "id" UUID NOT NULL,
    "sequence" INTEGER NOT NULL,
    "claimed_by" TEXT,
    "claimed_at" TIMESTAMPTZ(3),

    CONSTRAINT "job_claim_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "foundation_spike"."bigint_probe" (
    "id" UUID NOT NULL,
    "amount_minor" BIGINT NOT NULL,

    CONSTRAINT "bigint_probe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "foundation_spike"."constraint_probe" (
    "id" UUID NOT NULL,
    "scope_key" TEXT NOT NULL,
    "is_default" BOOLEAN NOT NULL DEFAULT false,
    "amount_minor" BIGINT NOT NULL,

    CONSTRAINT "constraint_probe_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "foundation_spike"."protected_entry" (
    "id" UUID NOT NULL,
    "note" TEXT NOT NULL,
    "amount_minor" BIGINT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "protected_entry_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "job_claim_sequence_key" ON "foundation_spike"."job_claim"("sequence");

-- ---------------------------------------------------------------------------
-- Custom SQL (hand-written and reviewed; not generated by Prisma).
-- ADR-002 section 5: generated migrations are extended with constraints,
-- partial indexes and privileges that the Prisma schema cannot express.
-- ---------------------------------------------------------------------------

-- CHECK constraint: amounts are non-negative minor units.
ALTER TABLE "foundation_spike"."constraint_probe"
    ADD CONSTRAINT "constraint_probe_amount_minor_non_negative" CHECK ("amount_minor" >= 0);

-- Partial unique index: at most one default row per scope_key.
CREATE UNIQUE INDEX "constraint_probe_one_default_per_scope"
    ON "foundation_spike"."constraint_probe" ("scope_key")
    WHERE "is_default";

-- Privileges. Explicit grants only: there are no default privileges, so a new
-- table is inaccessible to the application role until a migration grants it.
REVOKE ALL ON SCHEMA "foundation_spike" FROM PUBLIC;
GRANT USAGE ON SCHEMA "foundation_spike" TO tali_app;

GRANT SELECT, INSERT, UPDATE, DELETE ON
    "foundation_spike"."transaction_probe",
    "foundation_spike"."job_claim",
    "foundation_spike"."bigint_probe",
    "foundation_spike"."constraint_probe"
    TO tali_app;

-- Append-only stand-in (the pattern for ledger/audit tables): the application
-- role may read and insert, never update, delete or truncate. Corrections are
-- new rows. The owner/migration role keeps full DDL capability.
GRANT SELECT, INSERT ON "foundation_spike"."protected_entry" TO tali_app;
REVOKE UPDATE, DELETE, TRUNCATE ON "foundation_spike"."protected_entry" FROM tali_app;
