/**
 * @tali/shared: HTTP and sync wire contracts only (Zod). No business logic and
 * no utilities; pure business primitives belong in @tali/domain/kernel.
 */
export type { ErrorEnvelope } from "./contracts/http/error-envelope.js";
export { ErrorCodeSchema, ErrorEnvelopeSchema } from "./contracts/http/error-envelope.js";
export type { LivenessResponse, ReadinessResponse } from "./contracts/http/health.js";
export { DependencyStatusSchema, LivenessResponseSchema, ReadinessResponseSchema } from "./contracts/http/health.js";
export type { MoneyWire } from "./contracts/http/money.js";
export { CurrencyCodeWireSchema, MinorUnitsStringSchema, MoneyWireSchema } from "./contracts/http/money.js";
export type { QuantityWire } from "./contracts/http/quantity.js";
export { QuantityMinorStringSchema, QuantityWireSchema, UnitCodeWireSchema } from "./contracts/http/quantity.js";
export type {
  AddPackRequest,
  ArchiveCategoryRequest,
  ArchiveProductRequest,
  CategoriesResponse,
  CategoryListParams,
  CategoryResponse,
  CreateCategoryRequest,
  CreateProductRequest,
  PackListParams,
  PackResponse,
  PacksResponse,
  PriceHistoryEntryResponse,
  PriceHistoryResponse,
  ProductListParams,
  ProductResponse,
  ProductsResponse,
  ReactivateProductRequest,
  SetSellingPriceRequest,
  UnitResponse,
  UnitsResponse,
  UpdateCategoryRequest,
  UpdateProductRequest,
} from "./contracts/http/catalog.js";
export {
  AddPackRequestSchema,
  ArchiveCategoryRequestSchema,
  ArchiveProductRequestSchema,
  CatalogStatusWireSchema,
  CategoriesResponseSchema,
  CategoryListQuerySchema,
  CategoryPathSchema,
  CategoryResponseSchema,
  CreateCategoryRequestSchema,
  CreateProductRequestSchema,
  PackFactorMinorWireSchema,
  PackListQuerySchema,
  PackPathSchema,
  PackResponseSchema,
  PacksResponseSchema,
  PackStatusWireSchema,
  PriceHistoryEntryResponseSchema,
  PriceHistoryResponseSchema,
  ProductListQuerySchema,
  ProductPathSchema,
  ProductResponseSchema,
  ProductsResponseSchema,
  ReactivateProductRequestSchema,
  SetSellingPriceRequestSchema,
  UnitKindWireSchema,
  UnitResponseSchema,
  UnitsResponseSchema,
  UpdateCategoryRequestSchema,
  UpdateProductRequestSchema,
} from "./contracts/http/catalog.js";
export type { LocalSignInRequest, LocalSignInResponse } from "./contracts/http/local-sign-in.js";
export { LocalSignInRequestSchema, LocalSignInResponseSchema } from "./contracts/http/local-sign-in.js";
export type {
  BusinessResponse,
  CreateBusinessRequest,
  CreateBusinessResponse,
  CurrentUserResponse,
  LocationResponse,
  LocationsResponse,
  MembersResponse,
  MyBusinessesResponse,
  PageQuery,
  RegisterCurrentUserRequest,
} from "./contracts/http/tenancy.js";
export {
  BusinessPathSchema,
  BusinessResponseSchema,
  CreateBusinessRequestSchema,
  CreateBusinessResponseSchema,
  CurrentUserResponseSchema,
  EmptyQuerySchema,
  IdempotencyKeyHeaderSchema,
  LocationResponseSchema,
  LocationStatusWireSchema,
  LocationsResponseSchema,
  MembershipRoleWireSchema,
  MembershipStatusWireSchema,
  MembersResponseSchema,
  MyBusinessesResponseSchema,
  PageQuerySchema,
  RegisterCurrentUserRequestSchema,
} from "./contracts/http/tenancy.js";
export type {
  AcceptInvitationRequest,
  AcceptInvitationResponse,
  ChangeMemberRoleRequest,
  CreateInvitationRequest,
  CreateInvitationResponse,
  DeviceResponse,
  DevicesResponse,
  InvitationResponse,
  MemberChangeResponse,
  MemberStatusChangeRequest,
  RegisterDeviceRequest,
  RegisterDeviceResponse,
  RevokeDeviceResponse,
  RevokeInvitationResponse,
  UpdateBusinessNameRequest,
} from "./contracts/http/team.js";
export {
  AcceptInvitationRequestSchema,
  AcceptInvitationResponseSchema,
  ChangeMemberRoleRequestSchema,
  CreateInvitationRequestSchema,
  CreateInvitationResponseSchema,
  DEVICE_CREDENTIAL_HEADER,
  DEVICE_ID_HEADER,
  DevicePathSchema,
  DevicePlatformWireSchema,
  DeviceResponseSchema,
  DevicesResponseSchema,
  DeviceStatusWireSchema,
  EmptyBodySchema,
  InvitableRoleWireSchema,
  InvitationPathSchema,
  InvitationResponseSchema,
  InvitationStatusWireSchema,
  MemberChangeResponseSchema,
  MemberPathSchema,
  MemberStatusChangeRequestSchema,
  RegisterDeviceRequestSchema,
  RegisterDeviceResponseSchema,
  RevokeDeviceResponseSchema,
  RevokeInvitationResponseSchema,
  UpdateBusinessNameRequestSchema,
} from "./contracts/http/team.js";
