-- CreateTable
CREATE TABLE "business_invitations" (
    "business_id" UUID NOT NULL,
    "id" UUID NOT NULL,
    "token_hash" BYTEA NOT NULL,
    "role" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "expires_at" TIMESTAMPTZ(3) NOT NULL,
    "created_by_membership_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL,
    "accepted_by_membership_id" UUID,
    "accepted_at" TIMESTAMPTZ(3),
    "revoked_by_membership_id" UUID,
    "revoked_at" TIMESTAMPTZ(3),

    CONSTRAINT "business_invitations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "devices" (
    "business_id" UUID NOT NULL,
    "id" UUID NOT NULL,
    "platform" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "credential_hash" BYTEA NOT NULL,
    "status" TEXT NOT NULL,
    "registered_by_membership_id" UUID NOT NULL,
    "registered_at" TIMESTAMPTZ(3) NOT NULL,
    "revoked_by_membership_id" UUID,
    "revoked_at" TIMESTAMPTZ(3),

    CONSTRAINT "devices_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "business_invitations_token_hash_key" ON "business_invitations"("token_hash");

-- CreateIndex
CREATE INDEX "business_invitations_business_id_status_idx" ON "business_invitations"("business_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "business_invitations_business_id_id_key" ON "business_invitations"("business_id", "id");

-- CreateIndex
CREATE INDEX "devices_business_id_status_idx" ON "devices"("business_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "devices_business_id_id_key" ON "devices"("business_id", "id");

-- AddForeignKey
ALTER TABLE "business_audit_records" ADD CONSTRAINT "business_audit_records_business_id_device_id_fkey" FOREIGN KEY ("business_id", "device_id") REFERENCES "devices"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "business_invitations" ADD CONSTRAINT "business_invitations_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "business_invitations" ADD CONSTRAINT "business_invitations_business_id_created_by_membership_id_fkey" FOREIGN KEY ("business_id", "created_by_membership_id") REFERENCES "business_memberships"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "business_invitations" ADD CONSTRAINT "business_invitations_business_id_accepted_by_membership_id_fkey" FOREIGN KEY ("business_id", "accepted_by_membership_id") REFERENCES "business_memberships"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "business_invitations" ADD CONSTRAINT "business_invitations_business_id_revoked_by_membership_id_fkey" FOREIGN KEY ("business_id", "revoked_by_membership_id") REFERENCES "business_memberships"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "devices" ADD CONSTRAINT "devices_business_id_fkey" FOREIGN KEY ("business_id") REFERENCES "businesses"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "devices" ADD CONSTRAINT "devices_business_id_registered_by_membership_id_fkey" FOREIGN KEY ("business_id", "registered_by_membership_id") REFERENCES "business_memberships"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "devices" ADD CONSTRAINT "devices_business_id_revoked_by_membership_id_fkey" FOREIGN KEY ("business_id", "revoked_by_membership_id") REFERENCES "business_memberships"("business_id", "id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- ---------------------------------------------------------------------------
-- Custom SQL (hand-written and reviewed; not generated by Prisma).
-- Build 1 Slice 5 (docs/plans/003-build-1-identity-tenancy.md; ADR-005
-- sections 14, 15 and 20).
--
-- The composite tenant foreign keys above are generated from the Prisma
-- schema, including the new (business_id, device_id) reference from business
-- audit records. This section adds CHECK constraints and privileges. Every
-- object here is listed in scripts/verify-schema.mjs. RLS stays off. No
-- business rule lives in the database: there are no triggers or functions.
-- Only 32-byte SHA-256 digests of one-time secrets are stored, never the
-- plaintext.
-- ---------------------------------------------------------------------------

-- business_invitations: an invitation grants one of the four invitable roles
-- (never OWNER). EXPIRED is derived from expires_at and never stored. The
-- acceptance and revocation columns are set together and only in their status.
ALTER TABLE "business_invitations"
    ADD CONSTRAINT "business_invitations_token_hash_length" CHECK (octet_length("token_hash") = 32),
    ADD CONSTRAINT "business_invitations_role_valid" CHECK ("role" IN ('MANAGER', 'CASHIER', 'STOCK_KEEPER', 'ACCOUNTANT')),
    ADD CONSTRAINT "business_invitations_status_valid" CHECK ("status" IN ('PENDING', 'ACCEPTED', 'REVOKED')),
    ADD CONSTRAINT "business_invitations_expires_after_created" CHECK ("expires_at" > "created_at"),
    ADD CONSTRAINT "business_invitations_accepted_shape" CHECK (
        ("status" = 'ACCEPTED') = ("accepted_by_membership_id" IS NOT NULL)
        AND ("accepted_by_membership_id" IS NULL) = ("accepted_at" IS NULL)
    ),
    ADD CONSTRAINT "business_invitations_revoked_shape" CHECK (
        ("status" = 'REVOKED') = ("revoked_by_membership_id" IS NOT NULL)
        AND ("revoked_by_membership_id" IS NULL) = ("revoked_at" IS NULL)
    ),
    ADD CONSTRAINT "business_invitations_accepted_in_window" CHECK ("accepted_at" IS NULL OR ("accepted_at" >= "created_at" AND "accepted_at" < "expires_at")),
    ADD CONSTRAINT "business_invitations_revoked_after_created" CHECK ("revoked_at" IS NULL OR "revoked_at" >= "created_at");

-- devices: Android is the only registrable platform in Build 1. The label is
-- the trimmed 1..60 character display text from the domain contract.
ALTER TABLE "devices"
    ADD CONSTRAINT "devices_credential_hash_length" CHECK (octet_length("credential_hash") = 32),
    ADD CONSTRAINT "devices_platform_valid" CHECK ("platform" IN ('ANDROID')),
    ADD CONSTRAINT "devices_label_length" CHECK (char_length("label") BETWEEN 1 AND 60),
    ADD CONSTRAINT "devices_label_trimmed" CHECK ("label" = btrim("label")),
    ADD CONSTRAINT "devices_status_valid" CHECK ("status" IN ('ACTIVE', 'REVOKED')),
    ADD CONSTRAINT "devices_revoked_shape" CHECK (
        ("status" = 'REVOKED') = ("revoked_by_membership_id" IS NOT NULL)
        AND ("revoked_by_membership_id" IS NULL) = ("revoked_at" IS NULL)
    ),
    ADD CONSTRAINT "devices_revoked_after_registered" CHECK ("revoked_at" IS NULL OR "revoked_at" >= "registered_at");

-- Privileges: read, create and change state; never DELETE or TRUNCATE
-- (ADR-005 section 20). UPDATE also backs the SELECT ... FOR UPDATE row locks.
-- One statement per table, so the migration scan in verify-schema.mjs sees
-- each grant next to its table name.
GRANT SELECT, INSERT, UPDATE ON "business_invitations" TO tali_app;
GRANT SELECT, INSERT, UPDATE ON "devices" TO tali_app;
