// @ts-check
/**
 * Generates the Tali time-zone reference dataset (plan 003 section 13.4) from
 * an extracted IANA tzdata release. Run it only when the pinned release is
 * updated, then review the diff:
 *
 *   node tooling/timezone-reference/generate.mjs <extracted-tzdata-dir> <sha256-of-tzdata-archive>
 *
 * The output is pure data with no runtime dependency. Zone lines define
 * canonical primary zones; Link lines (including "backward") define aliases,
 * which are resolved to their canonical target.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const SOURCE_FILES = [
  "africa",
  "antarctica",
  "asia",
  "australasia",
  "europe",
  "northamerica",
  "southamerica",
  "etcetera",
  "backward",
];
const OUTPUT = "packages/domain/src/modules/business/time-zone-reference.ts";

const [sourceDir, archiveSha256] = process.argv.slice(2);
if (sourceDir === undefined || archiveSha256 === undefined || !/^[0-9a-f]{64}$/i.test(archiveSha256)) {
  console.error("usage: generate.mjs <extracted-tzdata-dir> <sha256-of-tzdata-archive>");
  process.exit(2);
}

const version = readFileSync(join(sourceDir, "version"), "utf8").trim();
if (!/^[0-9]{4}[a-z]$/.test(version)) throw new Error(`unexpected tzdata version "${version}"`);

/** @type {Set<string>} */
const zones = new Set();
/** @type {Map<string, string>} */
const links = new Map();

for (const file of SOURCE_FILES) {
  for (const rawLine of readFileSync(join(sourceDir, file), "utf8").split("\n")) {
    const line = rawLine.replace(/#.*$/, "").trim();
    const zone = /^Zone\s+(\S+)/.exec(line);
    if (zone?.[1] !== undefined) {
      zones.add(zone[1]);
      continue;
    }
    const link = /^Link\s+(\S+)\s+(\S+)$/.exec(line);
    if (link?.[1] !== undefined && link[2] !== undefined) {
      links.set(link[2], link[1]);
    }
  }
}

/** @param {string} name */
function resolve(name) {
  let current = name;
  for (let hops = 0; hops < 8; hops += 1) {
    if (zones.has(current)) return current;
    const next = links.get(current);
    if (next === undefined) throw new Error(`link "${name}" does not resolve to a Zone`);
    current = next;
  }
  throw new Error(`link chain too long for "${name}"`);
}

const aliases = [...links.keys()]
  .filter((name) => !zones.has(name))
  .sort()
  .map((name) => [name, resolve(name)]);
const canonical = [...zones].sort();

const folded = new Set();
for (const name of [...canonical, ...aliases.map(([alias]) => alias)]) {
  const key = name.toLowerCase();
  if (folded.has(key)) throw new Error(`names differ only by case: "${name}"`);
  folded.add(key);
}

const output = `/**
 * Tali time-zone reference dataset (plan 003 section 13.4). GENERATED by
 * tooling/timezone-reference/generate.mjs from IANA tzdata ${version}
 * (tzdata${version}.tar.gz, SHA-256 ${archiveSha256.toLowerCase()}). Do not edit by hand;
 * updating the release is a reviewed change.
 */

export const TIME_ZONE_REFERENCE_VERSION = "tzdata-${version}";

/** Canonical primary zones (tzdb Zone entries). */
export const CANONICAL_TIME_ZONES: readonly string[] = [
${canonical.map((name) => `  "${name}",`).join("\n")}
];

/** Recognized aliases (tzdb Link entries) mapped to their canonical primary zone. */
export const TIME_ZONE_ALIASES: readonly (readonly [alias: string, canonical: string])[] = [
${aliases.map(([alias, target]) => `  ["${alias}", "${target}"],`).join("\n")}
];
`;

writeFileSync(OUTPUT, output, "utf8");
console.log(`wrote ${OUTPUT}: ${canonical.length} canonical zones, ${aliases.length} aliases (tzdata ${version})`);
